### PR TITLE
Arm stuck check

### LINKED ISSUE #140: Detect when Arm is stuck and automatically stop motor to prevent rope from snapping/unwinding
There have been multiple times during practice that the arm/rope have snapped because it was stuck on something and/or the limit switches are broken/misaligned.

We should be able to use the encoder to augment the ArmSafety code to detect if the arm if stuck when moving down/up.

### PR DESCRIPTION
**Pull request by ParkerMeyers**
Closes #140

### CODE REVIEW

File: src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java [hunk 1]
```diff
@@ -82,6 +84,9 @@ public final void initialize() {
 
   @Override
   public final void execute() {
+    if (isArmStuck()) {
+      currentCommand = ArmCommand.EMERGENCY_STOP;
+    }
```
Comment (BrownGenius) [inline src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:89]: This section needs to be moved to below the `executeWithSafety()` call.  Otherwise, the child class may override the currentCommand by calling `up()` or `down`.   So, we need to implement all safety checks AFTER the child has been called.

File: src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java [hunk 2]
```diff
@@ -167,5 +172,22 @@ public final boolean isFinished() {
...
+
+  private boolean isArmStuck() {
+    // check the rate of change of the arm position
+    // if there is no change, then the rope is broken
+
+    double currentSpeed = Math.abs(arm.getVelocity());
+
+    // start a timer to see if the rope is stuck for a while
+    // if it is, then we need to stop the arm
+    if (currentSpeed < 0.75) {
```
Comment (BrownGenius) [inline src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:184]: The 0.75 should be in ArmConstants.  Unless you already know it, we also need to verify the nominal speed of the arm when everything is working as expected.

File: src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java [hunk 3]
```diff
@@ -167,5 +172,22 @@ public final boolean isFinished() {
    * execution of the command
    */
   public void initializeWithSafety() {}
-  ;
+
+  private boolean isArmStuck() {
```
Comment (BrownGenius) [inline src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:176]: Instead of looking at the currentSpeed, I was thinking that we could look at if the position has changed since the last execution.  So, we'd have to remember the previousPosition and then if the position is the same for X calls in a row, then we assume the arm is stuck.

File: src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java [hunk 4]
```diff
@@ -167,5 +172,22 @@ public final boolean isFinished() {
...
+    // start a timer to see if the rope is stuck for a while
+    // if it is, then we need to stop the arm
+    if (currentSpeed < 0.75) {
+      timer.start();
+    } else {
+      timer.stop();
+      timer.reset();
+    }
+
+    return timer.hasElapsed(1.0);
```
Comment (BrownGenius) [inline src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:191]: 1 second may be too long to wait to prevent damage to the Arm.  This value should also be in ArmConstants.

**Review by BrownGenius — CHANGES_REQUESTED** [review]
Hi Parker, thanks for taking a stab at this change.  Please make the requested changes!

File: src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java (hunk 3 above)
Comment (ParkerMeyers) [reply src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:176]: Is there a reason for this? They should do the same thing

Comment (BrownGenius) [reply src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:176]: I agree both ways should work.  In the end, we expect a the position to change by some _delta_ on every cycle.  We can detect it using position or velocity....we just need to calibrate the values accordingly.

Using currentSpeed requires us to know the set/expected speed to determine the "stuck" position.  Fortunately, the way the _current_ arm is physically designed, the speed is relatively constant.  _We should log the actual returned velocity returned by the encoder_ to see the range of values that are returned and set the "minSpeed" value accordingly.   FYI, if we ever decide to implement #127, the setSpeed needs to be taken into account, also.

In the end, we just need to detect the "stuck" condition _as fast as possible_ to prevent damage to the arm.

Comment (loafdog) [reply src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:176]: Maybe can check two things.. if the motor speed is not zero and encoder distance is not changing, the arm is stuck.

Comment (BrownGenius) [reply src/main/java/bhs/devilbotz/commands/arm/ArmSafety.java:182]: speed seems to work fine (as expected). @joshuman had to tweak the values to match the actual values reported from the encoder.getRate().  The typical rate is ~125-175, so we set the "stick" value to 75.  The code does seem to work in testing. When the arm is moving up, manually stopping the arm triggers the code correctly.  When the arm is moving down, the code does eventually trigger, but by the time it stops the arm, there is already too much tension on the arm.  We can maybe tweak tweak the values, but nonetheless, the code as-is is better than not having anything.

**Review by BrownGenius — COMMENTED** [review]
Looks good to me, but need someone else to review/approve

**Review by BrownGenius — APPROVED** [review]

**Review by ParkerMeyers — COMMENTED** [review]
Looks good, i cant approve it because its my PR but I call this approved

**Comment by BrownGenius** [comment]
> Looks good, i cant approve it because its my PR but I call this approved

LOL. Ok, I'll squash and merge.  It's weird how the PR is always linked to the original requestor and not the last person who modified the branch.
